package com.huan.mapper;

import com.huan.model.ArticleType;

import java.util.List;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    ArticleType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    List<ArticleType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int updateByPrimaryKey(ArticleType record);
}