package com.huan.mapper;

import com.huan.model.ArticleList;

import java.util.List;

public interface ArticleListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int insert(ArticleList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    ArticleList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    List<ArticleList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_list
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    int updateByPrimaryKey(ArticleList record);
}