package com.huan.model;

public class ArticleList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.id
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.subject
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.create_time
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.user_id
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.type
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.img_url
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_list.content
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.id
     *
     * @return the value of article_list.id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.id
     *
     * @param id the value for article_list.id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.subject
     *
     * @return the value of article_list.subject
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.subject
     *
     * @param subject the value for article_list.subject
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.create_time
     *
     * @return the value of article_list.create_time
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.create_time
     *
     * @param createTime the value for article_list.create_time
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.user_id
     *
     * @return the value of article_list.user_id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.user_id
     *
     * @param userId the value for article_list.user_id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.type
     *
     * @return the value of article_list.type
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.type
     *
     * @param type the value for article_list.type
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.img_url
     *
     * @return the value of article_list.img_url
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.img_url
     *
     * @param imgUrl the value for article_list.img_url
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_list.content
     *
     * @return the value of article_list.content
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_list.content
     *
     * @param content the value for article_list.content
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}