package com.huan.model;

public class ArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.id
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.code
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_type.name
     *
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.id
     *
     * @return the value of article_type.id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.id
     *
     * @param id the value for article_type.id
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.code
     *
     * @return the value of article_type.code
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.code
     *
     * @param code the value for article_type.code
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_type.name
     *
     * @return the value of article_type.name
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_type.name
     *
     * @param name the value for article_type.name
     * @mbg.generated Thu Jan 12 16:49:55 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}